version: '3.8'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - diary_data:/app/data
    environment:
      - PYTHONPATH=/app
    user: root
    command: >
      bash -c "
        mkdir -p /app/data &&
        chown -R sshuser:sshuser /app/data &&
        chmod -R 777 /app/data &&
        su sshuser -c 'streamlit run src/app.py --server.address 0.0.0.0'
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  diary_data: