version: '3.8'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - streamlit_data:/app/data
    environment:
      - ENVIRONMENT=development
    env_file:
      - .env
    restart: unless-stopped
    command: >
      bash -c "
        sudo chown -R vscode:vscode /app/data &&
        streamlit run src/app.py --server.address 0.0.0.0 --server.runOnSave true
      "
    user: "1000:1000"

volumes:
  streamlit_data: