version: '3.8'
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - diary_data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "
        python src/mock_data.py &&
        streamlit run src/app.py --server.address 0.0.0.0
      "

volumes:
  diary_data: